"""add inviter id

Revision ID: 98d8e61a48ee
Revises: f9e2871666eb
Create Date: 2022-03-19 11:24:19.417460

"""
from alembic import op
import sqlalchemy as sa
import app.utils.custom_fields
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98d8e61a48ee'
down_revision = 'f9e2871666eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussions_participants_relation', sa.Column('id', postgresql.UUID(), nullable=False))
    op.add_column('discussions_participants_relation', sa.Column('inviter_id', postgresql.UUID(), nullable=False))
    op.create_foreign_key(None, 'discussions_participants_relation', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discussions_participants_relation_inviter_id_fkey', 'discussions_participants_relation', type_='foreignkey')
    op.drop_column('discussions_participants_relation', 'inviter_id')
    op.drop_column('discussions_participants_relation', 'id')
    # ### end Alembic commands ###
